# Generated by Django 5.1 on 2024-08-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default="", max_length=150)),
                ("description", models.CharField(default="", max_length=250)),
            ],
        ),
    ]
